[workspace]
resolver = "2"
members = [
    "programs/system",
    "programs/token",
    "programs/token2022",
    "sdk/log/crate",
    "sdk/log/macro",
    "sdk/pinocchio",
    "sdk/pubkey",
]

[workspace.package]
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/febo/pinocchio"

[workspace.dependencies]
five8_const = "0.1.3"
pinocchio = { path = "sdk/pinocchio", version = "0.6" }
pinocchio-pubkey = { path = "sdk/pubkey", version = "0.2.1" }
